name: dementia_care
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  geolocator: ^10.1.0
  flutter_native_splash: ^2.3.10
  table_calendar: ^3.0.9
  accordion: ^2.6.0
  flutter_launcher_icons: "^0.13.1"
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.6
  http: ^1.1.2
  firebase_auth: ^4.17.8
  firebase_storage: ^11.6.9
  cloud_firestore: ^4.15.8
  firebase_messaging: ^14.7.19
  firebase_core: ^2.27.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  avatar_glow: ^3.0.1
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter_launcher_icons :
  android: "launcher_icon"
  ios: true
  image_path: assets/images/logo.jpeg
  min_sdk_android: 26


flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/icons/
     - assets/fonts/
  fonts:
    - family: Berlin Sans FB
      fonts:
        - asset: assets/fonts/Berlin Sans FB Regular.ttf
